add log transformation for scatterplot
insightsengineering/teal.modules.general pull request #448
Opened 2022-08-24 14:37 UTC by nikolas-burkoff

Closes #437 

FYI @donyunardi

Test with roxygen examples

![image](https://user-images.githubusercontent.com/15201933/186446541-6db16547-a459-44e3-871d-40ea95a27df6.png)
![image](https://user-images.githubusercontent.com/15201933/186446631-62f13f9d-bab7-4b65-879c-1a8e607e3964.png)
![image](https://user-images.githubusercontent.com/15201933/186446726-187cbef1-7648-4ace-8cd8-71ec19203f31.png)

And reflected in the SRC:
![image](https://user-images.githubusercontent.com/15201933/186446875-c5f3579a-ecc1-4280-938d-b0b2fbb118d4.png)

2022-08-24 14:47 UTC, nikolas-burkoff commented on NEWS.md
> +* Added log scale options in `tm_g_scatterplot`.
```suggestion
* Added log transformation options to `tm_g_scatterplot`.
```

2022-08-24 15:51 UTC, Polkas commented on R/tm_g_scatterplot.R
> +        checkboxInput(ns("log_x"), "Use log transformation for X variable", value = FALSE),
```suggestion
        checkboxInput(ns("log_x"), "Use log transformation", value = FALSE),
```

2022-08-24 15:51 UTC, Polkas commented on R/tm_g_scatterplot.R
> +        checkboxInput(ns("log_y"), "Use log transformation for Y variable", value = FALSE),
```suggestion
        checkboxInput(ns("log_y"), "Use log transformation", value = FALSE),
```

2022-08-24 15:53 UTC, Polkas approved these changes
LGTM, most important is the proper validation (> 0 values for log)

the only question could be the log scale, as for some statisticians a base is log10 not loge (the default R log).
log10(1e7) # = 7
log(1e7) # 16.1181

2022-08-24 16:32 UTC, donyunardi commented
Wow, thanks for picking this up so quickly @Polkas @nikolas-burkoff!

Hi @kumamiao,
Could you please advise on which log scale to use? Is it okay to use the default R log?
> the only question could be the log scale, as for some statisticians a base is log10 not loge (the default R log).
log10(1e7) # = 7
log(1e7) # 16.1181

2022-08-25 01:06 UTC, kumamiao commented
agree, if possible, would be great to add the flexibility to choose amongst log, log2 and log10 in R

2022-08-25 07:53 UTC, nikolas-burkoff commented
> agree, if possible, would be great to add the flexibility to choose amongst log, log2 and log10 in R

Done
![image](https://user-images.githubusercontent.com/15201933/186607734-e5ff3818-93e4-4d09-abf8-51be6650e787.png)

2022-08-25 08:50 UTC, Polkas requested changes
We find out the brush stops to work.

2022-08-25 10:00 UTC, nikolas-burkoff commented on R/tm_g_scatterplot.R
>        plot_brush <- brush$brush()
🤯

2022-08-25 10:05 UTC, nikolas-burkoff commented
> We find out the brush stops to work.

Should be fixed now

2022-08-25 12:12 UTC, Polkas commented on R/tm_g_scatterplot.R
> +            label = "Base",
```suggestion
            label = NULL,
```

2022-08-25 12:12 UTC, Polkas commented on R/tm_g_scatterplot.R
> +            label = "Base",
```suggestion
            label = NULL,
```

2022-08-25 12:12 UTC, Polkas commented on R/tm_g_scatterplot.R
> +            label = "Base",
The base already in the 2/3 of names

2022-08-25 12:13 UTC, Polkas commented on R/tm_g_scatterplot.R
> +            label = "Base",
The base already in the 2/3 of names

2022-08-25 12:33 UTC, merged