712 - `shinytest2` for `tm_variable_browser`
insightsengineering/teal.modules.general pull request #728
Opened 2024-04-12 12:41 UTC by averissimo

# Pull Request

Part of  #712

2024-04-16 11:58 UTC, m7pr requested changes
rename `set_module_input` to `set_active_module_input`

2024-04-16 11:58 UTC, m7pr commented on tests/testthat/test-shinytest2-tm_variable_browser.R
> +    app_driver$set_module_input(
```suggestion
    app_driver$set_active_module_input(
```

2024-04-16 11:58 UTC, m7pr commented on tests/testthat/test-shinytest2-tm_variable_browser.R
> +    app_driver$set_module_input(
```suggestion
    app_driver$set_active_module_input(
```

2024-04-16 11:58 UTC, m7pr commented on tests/testthat/test-shinytest2-tm_variable_browser.R
> +  app_driver$set_module_input("outlier_definition_slider", 2)
```suggestion
  app_driver$set_active_module_input("outlier_definition_slider", 2)
```

2024-04-16 11:58 UTC, m7pr commented on tests/testthat/test-shinytest2-tm_variable_browser.R
> +  app_driver$set_module_input("ggplot_theme", "bw")
```suggestion
  app_driver$set_active_module_input("ggplot_theme", "bw")
```

2024-04-16 11:58 UTC, m7pr commented on tests/testthat/test-shinytest2-tm_variable_browser.R
> +  app_driver$set_module_input("ggplot_theme", "light")
```suggestion
  app_driver$set_active_module_input("ggplot_theme", "light")
```

2024-04-16 11:58 UTC, m7pr commented on tests/testthat/test-shinytest2-tm_variable_browser.R
> +  app_driver$set_module_input("ggplot_theme", "dark")
```suggestion
  app_driver$set_active_module_input("ggplot_theme", "dark")
```

2024-04-16 11:58 UTC, m7pr commented on tests/testthat/test-shinytest2-tm_variable_browser.R
> +  app_driver$set_module_input("font_size", "8")
```suggestion
  app_driver$set_active_module_input("font_size", "8")
```

2024-04-16 11:58 UTC, m7pr commented on tests/testthat/test-shinytest2-tm_variable_browser.R
> +  app_driver$set_module_input("font_size", "20")
```suggestion
  app_driver$set_active_module_input("font_size", "20")
```

2024-04-16 11:58 UTC, m7pr commented on tests/testthat/test-shinytest2-tm_variable_browser.R
> +  app_driver$set_module_input("font_size", "15")
```suggestion
  app_driver$set_active_module_input("font_size", "15")
```

2024-04-16 11:58 UTC, m7pr commented on tests/testthat/test-shinytest2-tm_variable_browser.R
> +  app_driver$set_module_input("label_rotation", "25")
```suggestion
  app_driver$set_active_module_input("label_rotation", "25")
```

2024-04-16 11:58 UTC, m7pr commented on tests/testthat/test-shinytest2-tm_variable_browser.R
> +  app_driver$set_module_input("label_rotation", "0")
```suggestion
  app_driver$set_active_module_input("label_rotation", "0")
```

2024-04-16 11:58 UTC, m7pr commented on tests/testthat/test-shinytest2-tm_variable_browser.R
> +  app_driver$set_module_input("label_rotation", "90")
```suggestion
  app_driver$set_active_module_input("label_rotation", "90")
```

2024-04-18 10:54 UTC, kartikeyakirar requested changes
@averissimo test passes with warning. 
![image](https://github.com/insightsengineering/teal.modules.general/assets/6700955/808b2515-fcdf-4418-bf20-7c91d9f505d2)

Apart from that few additional request:

1: We don't need to call app_driver$expect_no_shiny_error() after every initialization.
2: Could you add tests to check the visibility of plots using app_driver$is_visible()?
2. is is possible to add test for checkbox (teat variable as factor)
<img width="689" alt="image" src="https://github.com/insightsengineering/teal.modules.general/assets/6700955/0a380c9e-6025-4c12-bc27-983d71d63769">

2024-04-18 12:48 UTC, averissimo commented
Thanks for the comments @kartikeyakirar.

I implemented them on the two new commits and split some of the tests that were too long / big scope.

> 1: We don't need to call app_driver$expect_no_shiny_error() after every initialization.

Does it seem fine as it is, or did you also mean to remove some of them after changing the inputs?

2024-04-18 13:32 UTC, kartikeyakirar commented
> Does it seem fine as it is, or did you also mean to remove some of them after changing the inputs?

I'm fine with either option, but since this additional test has already been checked and Marcin has removed it from another PR, let's keep it consistent.

2024-04-18 13:55 UTC, kartikeyakirar approved these changes
Great Work

2024-04-18 13:57 UTC, merged